### ISSUE TITLE
Cannot read property 'keywords' of undefined

### ISSUE THREAD

**Issue by chrisvdp** [jarias/generator-jhipster-ember#13]
Running on OSX 10.10.1, tried to generate a project and got 

? (1/7) What is the base name of your application? jhipster-ember
? (2/7) What is your default Java package name? com.mycompany.myapp
? (3/7) What is your application storage engine? MongoDB
? (4/7) Generate EmberJS UI? Yes
? (5/7) Use Stormpath as authentication provider? No
? (6/7) Use docker? No
? (7/7) Are you deploying to Heroku? No
version: 0.0.41
Cannot read property 'keywords' of undefined
TypeError: Cannot read property 'keywords' of undefined
    at Project.isEmberCLIAddon (/Users/cploeg/Web/node_modules/ember-cli/lib/models/project.js:31:18)
    at Class.module.exports.Command.extend._defaultBlueprint (/Users/cploeg/Web/node_modules/ember-cli/lib/commands/init.js:29:22)
    at Class.module.exports.Command.extend.run (/Users/cploeg/Web/node_modules/ember-cli/lib/commands/init.js:64:51)
    at Class.Command.validateAndRun (/Users/cploeg/Web/node_modules/ember-cli/lib/models/command.js:73:15)
    at /Users/cploeg/Web/node_modules/ember-cli/lib/cli/cli.js:54:22
    at $$$internal$$tryCatch (/Users/cploeg/Web/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
    at $$$internal$$invokeCallback (/Users/cploeg/Web/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
    at /Users/cploeg/Web/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1066:13
    at $$rsvp$asap$$flush (/Users/cploeg/Web/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
    at process._tickCallback (node.js:419:13)

**Comment by chrisvdp** [comment]
looks like it's an issue with ember-cli init
